name: DiscoSheep
main: Goldsack.DiscoSheep.DiscoSheep
version: 0.2
author: Goldsack
description: Gets sheeps into partymode
commands:
  discosheep:
    usage: |
           See /ds for more info on DiscoSheep
  discoparty:
    usage: |
           See /ds for more info on DiscoSheep
  disco:
    usage: |
           See /ds for more info on DiscoSheep
  ds:
    description: Gets sheeps into partymode
    usage: |
           /<command> color to toggle all sheeps going rainbowmode
           /<command> party to give every player a party time! Untz Untz!
           /<command> party [name] [sec] [sheeps] to give a player a big party
           /<command> party all [sec] [sheeps] to set how long a big party will last.
           /<command> stop to end a party